version: "3"

services:
  app1:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      MESSAGE: app1
    networks:
      - app-network
    ports:
      - "3000"
    restart: always
        
  app2:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      MESSAGE: app2
    networks: 
      - app-network
    ports:
      - "3000"
    restart: always
    
  nginx:
    image: nginx:alpine
    networks: 
      - app-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    ports:
      - "80:80"


networks: 
  app-network:
